"use client";

import React, { useState, useEffect } from "react";
import { supabase } from "@/utils/supabaseClient";
import { useRouter } from "next/navigation";
import { Sparkles, Loader2, Code, ArrowRight, User, Plus, X, RefreshCw, Upload } from "lucide-react";

interface Profile {
  username: string;
  avatar_url: string;
  stack_tags: string[];
}

export default function CreateProfilePage() {
  const router = useRouter();
  const [user, setUser] = useState<any>(null);
  const [loading, setLoading] = useState(true);
  const [saving, setSaving] = useState(false);
  const [errorMsg, setErrorMsg] = useState("");

  // Form states
  const [username, setUsername] = useState("");
  const [avatarUrl, setAvatarUrl] = useState("");
  const [tagInput, setTagInput] = useState("");
  const [stackTags, setStackTags] = useState<string[]>([]);

  useEffect(() => {
    supabase.auth.getSession().then(async ({ data: { session } }) => {
      if (!session?.user) {
        router.push("/login");
        return;
      }
      setUser(session.user);

      // Fetch the default profile row generated by database triggers
      try {
        const { data, error } = await supabase
          .from("profiles")
          .select("username, avatar_url, stack_tags")
          .eq("id", session.user.id)
          .single();

        if (data && !error) {
          setUsername(data.username || "");
          setAvatarUrl(data.avatar_url || `https://api.dicebear.com/7.x/bottts/svg?seed=${session.user.id}`);
          setStackTags(data.stack_tags || []);
          
          // If they already have onboarded (non-empty stack tags), send them to dashboard
          if (data.stack_tags && data.stack_tags.length > 0) {
            router.push("/dashboard");
            return;
          }
        }
      } catch (err) {
        // Fail silently without leaking database error traces to browser console
      } finally {
        setLoading(false);
      }
    });
  }, []);

  const handleFileUpload = (e: React.ChangeEvent<HTMLInputElement>) => {
    const file = e.target.files?.[0];
    if (!file) return;

    if (file.size > 2 * 1024 * 1024) {
      alert("Please select an image smaller than 2MB.");
      return;
    }

    const reader = new FileReader();
    reader.onload = (event) => {
      const img = new Image();
      img.onload = () => {
        const canvas = document.createElement("canvas");
        const MAX_WIDTH = 128;
        const MAX_HEIGHT = 128;
        let width = img.width;
        let height = img.height;

        if (width > height) {
          if (width > MAX_WIDTH) {
            height *= MAX_WIDTH / width;
            width = MAX_WIDTH;
          }
        } else {
          if (height > MAX_HEIGHT) {
            width *= MAX_HEIGHT / height;
            height = MAX_HEIGHT;
          }
        }

        canvas.width = width;
        canvas.height = height;
        const ctx = canvas.getContext("2d");
        if (ctx) {
          ctx.drawImage(img, 0, 0, width, height);
          const compressedBase64 = canvas.toDataURL("image/jpeg", 0.7);
          setAvatarUrl(compressedBase64);
        }
      };
      img.src = event.target?.result as string;
    };
    reader.readAsDataURL(file);
  };

  const handleRandomizeAvatar = () => {
    const randomSeed = Math.random().toString(36).substring(7);
    setAvatarUrl(`https://api.dicebear.com/7.x/bottts/svg?seed=${randomSeed}`);
  };

  const handleAddTag = (e: React.FormEvent) => {
    e.preventDefault();
    if (tagInput.trim() && !stackTags.includes(tagInput.trim())) {
      setStackTags([...stackTags, tagInput.trim()]);
      setTagInput("");
    }
  };

  const handleRemoveTag = (index: number) => {
    setStackTags(stackTags.filter((_, i) => i !== index));
  };

  const handleCompleteSetup = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!username.trim()) {
      setErrorMsg("Please specify a developer username.");
      return;
    }
    if (stackTags.length === 0) {
      setErrorMsg("Please add at least one tech stack specialization tag (e.g. Next.js, Python, CSS) to customize your public developer card.");
      return;
    }

    setSaving(true);
    setErrorMsg("");

    try {
      const { error } = await supabase
        .from("profiles")
        .update({
          username: username.trim(),
          avatar_url: avatarUrl.trim(),
          stack_tags: stackTags
        })
        .eq("id", user.id);

      if (error) throw error;

      router.push("/dashboard");
    } catch (err: any) {
      setErrorMsg("An unexpected error occurred while finalizing your profile. The username might already be in use. Please try another one.");
      setSaving(false);
    }
  };

  if (loading) {
    return (
      <div className="flex-1 flex items-center justify-center bg-bg min-h-screen">
        <Loader2 className="h-8 w-8 animate-spin text-accent" />
      </div>
    );
  }

  return (
    <div className="flex-1 flex items-center justify-center px-6 py-20 bg-bg relative min-h-screen">
      <div className="w-full max-w-2xl p-8 glass-panel border border-border relative z-10 shadow-2xl space-y-8">
        
        {/* Top visual neon accent line */}
        <div className="absolute top-0 left-0 right-0 h-1 bg-gradient-to-r from-accent via-accent2 to-accent" />

        <div className="text-center">
          <div className="inline-flex p-3 bg-surface border border-border text-accent mb-4">
            <Sparkles className="h-6 w-6" />
          </div>
          <h2 className="font-syne text-3xl font-extrabold tracking-tight mb-2">
            Initialize Your <span className="text-accent">Identity</span>
          </h2>
          <p className="text-xs text-text-muted max-w-md mx-auto">
            You are logging in for the first time. Complete your public developer signature card so developers can identify your projects and pitches.
          </p>
        </div>

        {errorMsg && (
          <div className="p-4 bg-warning-bg border border-warning-border text-accent2 text-xs">
            <span className="block font-semibold uppercase tracking-wider mb-1">Configuration Lock</span>
            {errorMsg}
          </div>
        )}

        <form onSubmit={handleCompleteSetup} className="space-y-6">
          <div className="grid grid-cols-1 md:grid-cols-3 gap-8 items-start">
            
            {/* Avatar Selection Column */}
            <div className="space-y-4 text-center glass-panel p-4 border border-border">
              <label className="block text-[10px] uppercase tracking-wider text-text-muted font-bold">
                Developer Signature
              </label>
              
              <div className="relative inline-block mx-auto border border-border p-1 bg-surface2">
                <img 
                  src={avatarUrl} 
                  alt="Avatar Preview" 
                  className="h-28 w-28 bg-[#151515]"
                />
              </div>

              <button
                type="button"
                onClick={handleRandomizeAvatar}
                className="w-full flex items-center justify-center gap-2 border border-border hover:border-accent bg-surface hover:text-accent py-2 text-xs font-semibold uppercase tracking-wider transition-colors cursor-pointer mb-2"
              >
                <RefreshCw className="h-3.5 w-3.5" />
                <span>Randomize Bot</span>
              </button>

              <div className="w-full">
                <input
                  type="file"
                  id="avatar-upload-onboarding"
                  accept="image/*"
                  onChange={handleFileUpload}
                  className="hidden"
                />
                <label
                  htmlFor="avatar-upload-onboarding"
                  className="w-full flex items-center justify-center gap-2 border border-border hover:border-accent2 bg-surface hover:text-accent2 py-2 text-xs font-semibold uppercase tracking-wider transition-colors cursor-pointer"
                >
                  <Upload className="h-3.5 w-3.5" />
                  <span>Upload Image</span>
                </label>
              </div>
            </div>

            {/* Form Details Column */}
            <div className="md:col-span-2 space-y-5">
              
              {/* Username field */}
              <div>
                <label htmlFor="username" className="block text-[10px] uppercase tracking-wider text-text-muted mb-2 font-bold">
                  Developer Username *
                </label>
                <div className="relative">
                  <input
                    type="text"
                    id="username"
                    placeholder="e.g. dev_stranger"
                    value={username}
                    onChange={(e) => setUsername(e.target.value.replace(/[^a-zA-Z0-9_-]/g, ""))}
                    required
                    className="w-full bg-surface border border-border text-text-primary px-4 py-2.5 pl-10 text-xs focus:border-accent focus:outline-none transition-all font-mono"
                  />
                  <User className="absolute left-3.5 top-3.5 h-4 w-4 text-text-muted" />
                </div>
                <span className="text-[10px] text-text-dim mt-1.5 block font-mono">
                  Only alphanumeric characters, dashes, and underscores permitted.
                </span>
              </div>

              {/* Avatar Url text input */}
              <div>
                <label htmlFor="avatarUrl" className="block text-[10px] uppercase tracking-wider text-text-muted mb-2 font-bold">
                  Custom Avatar Image / SVG URL
                </label>
                <input
                  type="text"
                  id="avatarUrl"
                  placeholder="https://example.com/avatar.png"
                  value={avatarUrl}
                  onChange={(e) => setAvatarUrl(e.target.value)}
                  className="w-full bg-surface border border-border text-text-primary px-4 py-2.5 text-xs focus:border-accent focus:outline-none transition-all font-mono"
                />
                <span className="text-[10px] text-text-dim mt-1.5 block font-mono">
                  Paste any custom image URL, or use the randomize seed button.
                </span>
              </div>

              {/* Specializations input */}
              <div>
                <label className="block text-[10px] uppercase tracking-wider text-text-muted mb-2 font-bold">
                  Specialization Tags *
                </label>
                <div className="flex gap-2 mb-3">
                  <input
                    type="text"
                    placeholder="e.g. Next.js, Rust, Tailwind"
                    value={tagInput}
                    onChange={(e) => setTagInput(e.target.value)}
                    className="flex-1 bg-surface border border-border text-text-primary px-4 py-2.5 text-xs focus:border-accent focus:outline-none transition-all font-mono"
                  />
                  <button
                    type="button"
                    onClick={handleAddTag}
                    className="bg-surface hover:bg-surface2 text-text-primary border border-border hover:border-accent px-4 text-xs font-bold uppercase cursor-pointer"
                  >
                    Add
                  </button>
                </div>

                <div className="flex flex-wrap gap-1.5">
                  {stackTags.map((tag, idx) => (
                    <span 
                      key={tag} 
                      className="inline-flex items-center gap-1 bg-surface2 border border-border text-text-primary text-[10px] px-2.5 py-1 font-mono uppercase tracking-wider"
                    >
                      <span>{tag}</span>
                      <button
                        type="button"
                        onClick={() => handleRemoveTag(idx)}
                        className="text-text-muted hover:text-accent2 transition-colors cursor-pointer"
                      >
                        <X className="h-3 w-3" />
                      </button>
                    </span>
                  ))}
                  {stackTags.length === 0 && (
                    <span className="text-xs text-text-dim italic font-mono">No specializations added yet.</span>
                  )}
                </div>
              </div>

            </div>
          </div>

          <div className="border-t border-border pt-6 flex justify-end">
            <button
              type="submit"
              disabled={saving}
              className="bg-accent hover:bg-accent2 text-bg hover:text-bg text-xs font-extrabold uppercase tracking-widest px-6 py-4 transition-all duration-300 flex items-center gap-2 cursor-pointer disabled:opacity-50"
            >
              {saving ? (
                <>
                  <Loader2 className="h-4 w-4 animate-spin" />
                  <span>Registering Signature...</span>
                </>
              ) : (
                <>
                  <span>Complete Onboarding</span>
                  <ArrowRight className="h-4 w-4" />
                </>
              )}
            </button>
          </div>

        </form>

      </div>
    </div>
  );
}
